import smtplib
from email.mime.text import MIMEText

# 🔽 Add your recipient email addresses inside the list below
emails = [
    "muskangupta56273@gmail.com",
    "piyupharande@gmail.com",
    "avimitrasaha@gmail.com",
    "ster.sayantan@gmail.com",
    "varshagari123@gmail.com",
    "rawatpvarun11@gmail.com",
    "jasleenmohanty16@gmail.com",
    "mdbasheeru06@gmail.com",
    "chittichitti885@gmail.com",
    "hrushithavennelaeagala2004@gmail.com",
    "mylapalligayathridevi@gmail.com",
    "rk62014072@gmail.com",
    "monisoni2223@gmail.com",
    "atchutaramanibonda2004@gmail.com",
    "adarirushitha2005@gmail.com",
    "kasireddymounika521@gmail.com",
    "nilesh.chauhan2004@gmail.com",
    "ayushchandrajaiswal12345678@gmail.com",
    "padmajyothi06@gmail.com",
    "yerravimala172@gmail.com",
    "kavyagandubelli208@gmail.com",
    "muskan35163@gmail.com",
    "souvikdas5504@gmail.com",
    "karrisaranya3333@gmail.com",
    "meenakshimosa@gmail.com",
    "saisree.r2005@gmail.com",
    "mounika383rayapati@gmail.com",
    "nandini28102003@gmail.com",
    "aparnakalla20@gmail.com",
    "japleenkaur2713@gmail.com",
    "chandrikapothala7@gmail.com",
    "srisaiamruthaveedhi@gmail.com",
    "shashankmilind447@gmail.com",
    "saumya2630@gmail.com",
    "dchirantan23@gmail.com",
    "sg068161@gmail.com",
    "vivekkanu125@gmail.com",
    "khushipremjaiswal@gmail.com",
    "pritiprangya245@gmail.com",
    "vaishnavishinde3107@gmail.com",
    "helisasaha@gmail.com",
    "mohammadashrafshaikh1@gmail.com",
    "koliomkar2003@gmail.com",
    "adityadhanraj072005@gmail.com",
    "rajmajumdar9942@gmail.com",
    "rahulbhati53514@gmail.com",
    "shrutimishra3124@gmail.com",
    "washiul92@gmail.com",
    "ayushkashyap338@gmail.com",
    "birajkuwar6@gmail.com",
    "ranitbag49@gmail.com",
    "sehermaniyar5@gmail.com",
    "aakashsharma7038@gmail.com",
    "sowmyatelu72@gmail.com",
    "ansamariamkuruvilla@gmail.com",
    "harshittiwari10112003@gmail.com",
    "tg9860313@gmail.com",
    "codewithraghu03@gmail.com",
    "mohitdubey8678@gmail.com",
    "venkatsaiponamala@gmail.com",
    "funwithrahul28@gmail.com",
    "toshinahatkar23@gmail.com",
    "t2samantan@gmail.com",
    "anushkamou12@gmail.com",
    "mahapatrapapun60@gmail.com",
    "amankumarsingh18114914@gmail.com",
    "amritamahato766@gmail.com",
    "vishal.p8070@gmail.com",
    "dsaiabhilipsa345@gmail.com",
    "priyanka.guddykri123@gmail.com",
    "abhiseknanda919@gmail.com",
    "almasimampatel@gmail.com",
    "eswarammakhandyapu@gmail.com",
    "yadavabhay2018@gmail.com",
    "saubhagyaranjanbehera64@gmail.com",
    "parimalamahadasu@gmail.com",
    "monalisapanda954@gmail.com",
    "anishashutoshnayak@gmail.com",
    "surajgupta5432@gmail.com",
    "knvaishnavi2004@gmail.com",
    "riddhikarm@gmail.com",
    "adigarlajyothika@gmail.com",
    "akellasuchitra2005@gmail.com",
    "divyakatadi@gmail.com",
    "tejasrikarri9@gmail.com",
    "hemamalinikanuri1946@gmail.com",
    "bhuvananaidu9333@gmail.com",
    "saioruganti796@gmail.com",
    "mishrarishi936@gmail.com",
    "ananyadutta950@gmail.com",
    "bhagabati.career@gmail.com",
    "hemainjarapu02@gmail.com",
    "deepikaryali369@gmail.com",
    "arnasarkar89@gmail.com",
    "sheema2565@gmail.com",
    "souravkaiborta1122@gmail.com",
    "priyadarshini862003@gmail.com",
    "kalyanaditya16@gmail.com",
    "achitkr0204@gmail.com",
    "honeyjain1523@gmail.com",
    "vaishnavibhandare215@gmail.com",
    "mounikasurupu@gmail.com",
    "akhilab636@gmail.com",
    "fashiyahashmi1@gmail.com",
    "tanishq.petlover@gmail.com",
    "karthikkunisetti1@gmail.com",
    "tmayank2006@gmail.com",
    "sunandasrivallik@gmail.com",
    "bindumadhavi2549@gmail.com",
    "anubhav323paul@gmail.com",
    "cypriankujur51@gmail.com",
    "santhilathasahu04@gmail.com",
    "sindhuja1887@gmail.com",
    "chandanasaladi6012@gmail.com",
    "beherarati18@gmail.com",
    "jayasrivadavalasa123@gmail.com",
    "kaif.ahmediembca2025@gmail.com",
    "meghanadangeti2705@gmail.com",
    "mondalsayandeep088@gmail.com",
    "sachinsingh841211@gmail.com",
    "priyanshipragya07@gmail.com",
    "tejaswanikonada16@gmail.com",
    "siddhujalota012@gmail.com",
    "keerthanasaligram70@gmail.com",
    "laharikamarripilli20@gmail.com",
    "navyatotakura2004@gmail.com",
    "bamariyamali@gmail.com",
    "venkatagovindkumarvanamadi@gmail.com",
    "harshithamarrapu513@gmail.com",
    "hemanjalireddychilla@gmail.com",
    "srilayasrilaya0@gmail.com",
    "ratnadeepguha15@gmail.com",
    "2004vts@gmail.com",
    "moizfarhan20103@gmail.com",
    "asapuadilakshmi@gmail.com",
    "navyasairavupalli1234@gmail.com",
    "lahariadhikarla04@gmail.com",
    "bhavanishankarsappa@gmail.com",
    "boddetipujithagayathri@gmail.com",
    "akashpotnuru914@gmail.com",
    "tumulahemasri@gmail.com",
    "rajasekharuriti2@gmail.com",
    "pragadavijayakumar.1@gmail.com",
    "pavanipalavalasa111@gmail.com",
    "harshagurugubelli04@gmail.com",
    "darshitha.tech@gmail.com",
    "aasthapaulnandi@gmail.com",
    "shubham101in@gmail.com",
    "ishaanraut02@gmail.com",
    "anilmahanty19@gmail.com",
    "saurabhraiji1977@gmail.com",
    "yogithamajji2023@gmail.com",
    "manasmishra6391@gmail.com",
    "chandanpradhankumar0876@gmail.com",
    "trineethrabollu@gmail.com",
    "shuvams302@gmail.com",
    "sreyadey01@gmail.com",
    "roysoni3010@gmail.com",
    "shubhamtiwary620@gmail.com",
    "ishitaiembca2025@gmail.com",
    "spriyadarsini993@gmail.com",
    "sidharthpradhan445@gmail.com",
    "vachana2603@gmail.com",
    "kansrali07@gmail.com",
    "meghanabhandary057@gmail.com",
    "debopriyasaha24@gmail.com",
    "swayam.04.prava@gmail.com",
    "bsayanibanerjee156@gmail.com",
    "vangapallisowjanya1912@gmail.com",
    "shivanimathapati22@gmail.com",
    "ksogalmath@gmail.com",
    "udaymanchu001@gmail.com",
    "nazshavi0@gmail.com",
    "abhinabadas02@gmail.com",
    "somyamoharana2003@gmail.com",
    "dishaghosal2004@gmail.com"
]


# ✉️ Email subject and body
subject = "i am a data center batch student from wipro"
body = """
Hello,

i have few doubs on the sections and the meetings 
those who know telugu reply back to this mail there is only two members
in my batch " im am 16th batch " i want to clarify about the log sheets 
modules, and the rps kindly reply to this main if any one who knows telugu

Regards,
Uday
"""


# 🔐 Your Gmail credentials
sender_email = "udaymanchu001@gmail.com"           # Replace with your Gmail
password = "eluc wrzq skue ddaq"     # Replace with your Gmail App Password (no spaces)

# ✅ Send email to all recipients
for recipient in emails:
    msg = MIMEText(body)
    msg["Subject"] = subject
    msg["From"] = sender_email
    msg["To"] = recipient

    try:
        # Use TLS (Port 587)
        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.starttls()  # Secure the connection
            server.login(sender_email, password)
            server.sendmail(sender_email, recipient, msg.as_string())

        print(f"✅ Email sent to: {recipient}")
    except Exception as e:
        print(f"❌ Failed to send to {recipient}: {e}")
